obj-m = ngtcp2_acktr.o ngtcp2_buf.o \
	ngtcp2_conversion.o ngtcp2_ksl.o ngtcp2_opl.o ngtcp2_pq.o \
	ngtcp2_rob.o ngtcp2_unreachable.o ngtcp2_addr.o ngtcp2_cc.o \
	ngtcp2_crypto.o ngtcp2_log.o ngtcp2_path.o ngtcp2_pv.o \
	ngtcp2_rst.o ngtcp2_vec.o ngtcp2_balloc.o ngtcp2_cid.o \
	ngtcp2_err.o ngtcp2_map.o ngtcp2_pkt.o ngtcp2_qlog.o \
	ngtcp2_rtb.o ngtcp2_version.o ngtcp2_bbr2.o \
	ngtcp2_conn.o ngtcp2_gaptr.o ngtcp2_mem.o \
	ngtcp2_pmtud.o ngtcp2_range.o ngtcp2_str.o \
	ngtcp2_window_filter.o ngtcp2_bbr.o ngtcp2_conv.o \
	ngtcp2_idtr.o ngtcp2_objalloc.o ngtcp2_ppe.o \
	ngtcp2_ringbuf.o ngtcp2_strm.o
